version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - choregarden-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/.env.json:/app/.env.json:ro
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - database
    networks:
      - choregarden-network
    env_file:
      - ./.env

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # Enable SSL in Postgres
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=trust"
    volumes:
      - choregarden-data:/var/lib/postgresql/data
      - ./database/certs:/var/lib/postgresql/certs:ro
      - ./database/certs/copy-certs-and-start.sh:/docker-entrypoint-initdb.d/copy-certs-and-start.sh:ro
    command: ["/bin/sh", "/var/lib/postgresql/certs/copy-certs-and-start.sh"]
    ports:
      - "5432:5432"
    networks:
      - choregarden-network
    env_file:
      - ./.env

volumes:
  choregarden-data:

networks:
  choregarden-network:
    driver: bridge