name: Deploy - Development

on:
  workflow_run:
    workflows: ["CI - Tests"]
    branches: [dev]
    types:
      - completed

jobs:
  deploy-frontend-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm run build

      - name: Deploy frontend to S3
        working-directory: ./frontend
        run: |
          aws s3 sync ./build s3://choregarden-frontend-dev --delete

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      - name: Update frontend config
        working-directory: ./infrastructure/envs/dev
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: |
          terraform init
          terraform apply -replace="module.frontend_static_site.aws_s3_object.frontend_config" -auto-approve

  deploy-backend-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Placeholder - Backend Dev Deployment
        run: |
          echo "Backend dev deployment would run here"
          echo "Target: Dev environment"

  deploy-db-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Placeholder - Database Dev Deployment
        run: |
          echo "Database dev deployment (migrations) would run here"
          echo "Target: Dev environment"
